### ISSUE TITLE
the inited project can not start with the entry point of `.ts` file

### ISSUE THREAD

**Issue by fofofofoxier** [reactiverse/es4x#109]
As the tile said, es4x seems not to be work with the `*.ts` entry-point file.
I inited the project as the [installing guide](https://reactiverse.io/es4x/start/install/) ,just changing the `index.js` with `index.ts`.
the content of `index.ts file`(located at the root dir of project) as follows:
```
/// <reference types="@vertx/core/runtime" />
// @ts-check
import { Router } from '@vertx/web';

const app = Router.router(vertx);

app.route('/').handler(function (ctx) {
  ctx.response().end('Hello from Vert.x Web!');
});

vertx.createHttpServer()
  .requestHandler(app)
  .listen(8080);
``` 

after typing in `npm start`,the error log is as follows
```
> social-vx-server@1.0.0 start /Users/liuchangxing/vertxTest/social-vx-server
> es4x-launcher

ES4X is using graaljs in interpreted mode! Add the JVMCI compiler module in order to run in optimal mode!
ModuleError: Module "./index.ts" was not found
	at <js> runMain(file:/Users/liuchangxing/vertxTest/social-vx-server/node_modules/.lib/es4x-0.8.0.jar!/io/reactiverse/es4x/jvm-npm.js:108:3597-3677)
	at org.graalvm.polyglot.Value.execute(Value.java:338)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.invokeMethod(GraalRuntime.java:188)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.main(GraalRuntime.java:156)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.main(GraalRuntime.java:34)
	at io.reactiverse.es4x.JSVerticleFactory$1.start(JSVerticleFactory.java:73)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Failed in deploying verticle caused by ModuleError: Module "./index.ts" was not found
	at <js> runMain(file:/Users/liuchangxing/vertxTest/social-vx-server/node_modules/.lib/es4x-0.8.0.jar!/io/reactiverse/es4x/jvm-npm.js:108:3597-3677)
	at org.graalvm.polyglot.Value.execute(Value.java:338)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.invokeMethod(GraalRuntime.java:188)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.main(GraalRuntime.java:156)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.main(GraalRuntime.java:34)
	at io.reactiverse.es4x.JSVerticleFactory$1.start(JSVerticleFactory.java:73)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
ModuleError: Module "./index.ts" was not found
	at <js> runMain(file:/Users/liuchangxing/vertxTest/social-vx-server/node_modules/.lib/es4x-0.8.0.jar!/io/reactiverse/es4x/jvm-npm.js:108:3597-3677)
	at org.graalvm.polyglot.Value.execute(Value.java:338)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.invokeMethod(GraalRuntime.java:188)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.main(GraalRuntime.java:156)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.main(GraalRuntime.java:34)
	at io.reactiverse.es4x.JSVerticleFactory$1.start(JSVerticleFactory.java:73)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:552)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fofofofoxier** [comment]
the project seems to be running with `*.js` file , but not with `*.ts`

**Comment by 943470549** [comment]
hha, change it to index.js

**Comment by pmlopes** [comment]
You will need a build step. See this comment:

https://github.com/reactiverse/es4x/issues/107#issuecomment-502450570

**Comment by fofofofoxier** [comment]
Thanks , this perfectly matched my problom.
