### ISSUE TITLE
Running example from front page throws ClassNotFound exception

### ISSUE THREAD

**Issue by nobleach** [reactiverse/es4x#150]
I'm attempting to follow the exact steps from the asciicast on es4x's home page.
My `example.js`:
```
console.log('Hello ', process.engine);
```
When I run `es4x ./example.js`. I get:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/graalvm/polyglot/io/FileSystem
        at io.reactiverse.es4x.ECMAEngine.newEngine(ECMAEngine.java:27)
        at io.reactiverse.es4x.ESVerticleFactory.init(ESVerticleFactory.java:30)
        at io.vertx.core.impl.DeploymentManager.registerVerticleFactory(DeploymentManager.java:321)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
        at io.vertx.core.impl.DeploymentManager.loadVerticleFactories(DeploymentManager.java:75)
        at io.vertx.core.impl.DeploymentManager.<init>(DeploymentManager.java:70)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:168)
        at io.vertx.core.impl.VertxImpl.vertx(VertxImpl.java:92)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:40)
        at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:32)
        at io.vertx.core.Vertx.vertx(Vertx.java:85)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:113)
        at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:278)
        at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
        at io.reactiverse.es4x.impl.command.ES4XRunCommand.run(ES4XRunCommand.java:72)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
        at io.reactiverse.es4x.ES4X.main(ES4X.java:49)
Caused by: java.lang.ClassNotFoundException: org.graalvm.polyglot.io.FileSystem
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 18 more
```

I don't know enough about GraalVM to know how to troubleshoot this.

**Comment by nobleach** [comment]
Very important piece that I missed. I needed to have my JDK set to GraalVM! (sdkman makes this trivial)

**Comment by IonelLupu** [comment]
@nobleach How did you fix it? My JDK is already set to GraalVM:

```sh
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
OpenJDK 64-Bit GraalVM CE 19.2.0.1 (build 25.222-b08-jvmci-19.2-b02, mixed mode)
```
I am seeing GraalVM on the last line but the front-page example still gives me the same error.

**Comment by IonelLupu** [comment]
Never mind. I forgot to change the JAVA_HOME environment variable to point to GraalVM. 

I just don't understand why I have to set the JDK AND the JAVA_HOME to GraalVM. Why not just set it once.....

**Comment by pmlopes** [comment]
@IonelLupu that was a bug fixed on https://github.com/reactiverse/es4x/commit/0a18246896fc4052528469bba15f1aacdaf4ab31#diff-b1582a0e028d50ad27847c02baeac0fd

In the next releases no variables need to be defined. So the rule is as follows:

If `JAVA_HOME` is set and `JAVA_HOME`/bin/java exists, take that as the java in your system.
If not, just take `java` as the java in your system.

This is how most/maybe all java related tools work. And allows the usage of multiple java runtimes in your machine.

**Comment by IonelLupu** [comment]
@pmlopes That's very cool. Thank you!

I am currently working on a framework written entirely in Typescript and I was wondering if it can run on top of es4x. It's just a prototype right now. You can find it at https://typetron.org .

I also did a small `hello world` benchmark on nodejs vs es4x and the results are not that different: nodejs(in cluster): 55K requests/s, es4x: 64k requests/s. I still don't know if it's worth it.

**Comment by pmlopes** [comment]
es4x doesn't run TS directly you still need to use the `tsc` to generate JS, it should theoretically work as long as there are no references to node native modules.

Regarding benchmarks, i don't know which flags did you use for es4x, but it seems you already get 16% perf improvement. The docs on performance are still on my todo, for example if you look at techempower this are the flags I use:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/es4x/es4x.dockerfile#L14-L27
