### ISSUE TITLE
question about adding log4js dependency

### ISSUE THREAD

**Issue by sephrouse** [reactiverse/es4x#191]
since ES4X aims to be the fastest js backend framework like express, how to use log4js to log backend? do you have any other logger plan?

not sure how to utilize npm packages to provide relevant service?

thanks in advance for your advice.

`npm install log4js --save`

`import {getLogger} from 'log4js';
...
const Logger = getLogger();
...
Logger.debug('xxxxxxxxxx');`

after npm start, console shows the below error

`Failed in deploying verticle caused by ModuleError: Module "tty" was not found
	at <js> Require.resolve(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:165:5324-5402)
	at <js> Require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:132:4365-4391)
	at <js> this.require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
	at <js> :anonymous(/home/sephrouse/projects/es4x/es4x_example/node_modules/debug/src/node.js:5:107-120)
	at <js> _load(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
	at <js> Require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
	at <js> this.require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
	at <js> :anonymous(/home/sephrouse/projects/es4x/es4x_example/node_modules/debug/src/index.js:9:352-371)
	at <js> _load(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
	at <js> Require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
	at <js> this.require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
	at <js> :anonymous(/home/sephrouse/projects/es4x/es4x_example/node_modules/log4js/lib/log4js.js:21:700-715)
	at <js> _load(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
	at <js> Require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
	at <js> this.require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
	at <js> :anonymous(/home/sephrouse/projects/es4x/es4x_example/dist/index.js:7:285-301)
	at <js> _load(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
	at <js> runMain(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:110:3648-3692)
	at org.graalvm.polyglot.Value.invokeMember(Value.java:457)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.main(GraalRuntime.java:148)
	at io.reactiverse.es4x.JSVerticleFactory$1.start(JSVerticleFactory.java:71)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
ModuleError: Module "tty" was not found
	at <js> Require.resolve(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:165:5324-5402)
	at <js> Require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:132:4365-4391)
	at <js> this.require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
	at <js> :anonymous(/home/sephrouse/projects/es4x/es4x_example/node_modules/debug/src/node.js:5:107-120)
	at <js> _load(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
	at <js> Require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
	at <js> this.require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
	at <js> :anonymous(/home/sephrouse/projects/es4x/es4x_example/node_modules/debug/src/index.js:9:352-371)
	at <js> _load(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
	at <js> Require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
	at <js> this.require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
	at <js> :anonymous(/home/sephrouse/projects/es4x/es4x_example/node_modules/log4js/lib/log4js.js:21:700-715)
	at <js> _load(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
	at <js> Require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
	at <js> this.require(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
	at <js> :anonymous(/home/sephrouse/projects/es4x/es4x_example/dist/index.js:7:285-301)
	at <js> _load(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
	at <js> runMain(file:/home/sephrouse/projects/es4x/es4x_example/node_modules/.lib/es4x-0.9.0.jar!/io/reactiverse/es4x/jvm-npm.js:110:3648-3692)
	at org.graalvm.polyglot.Value.invokeMember(Value.java:457)
	at io.reactiverse.es4x.impl.graal.GraalRuntime.main(GraalRuntime.java:148)
	at io.reactiverse.es4x.JSVerticleFactory$1.start(JSVerticleFactory.java:71)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by pmlopes** [comment]
`tty` is a node native module which isn't suported. Currently vertx offers a logging API (but it deprecated) which relies on the jvm so you could plug in any plugin to log to the console, file or network.

As it's a deprecated api this isn't a proper solution but a workaround for now...

**Comment by sephrouse** [comment]
Thanks for your comment. And also thank you for your effort on the ES4X.

Wish ES4X being popular in the near future.
