### ISSUE TITLE
Verify peerCertificateChain

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#320]
I reviewed both the vertx-js-web docs and early release docs of the ES4X web-client, but I see no mention on how to use the peerCertificateChain call. Is it supported in js/ES4X? If so, am I doing this correctly? I assume the test case below would either print the chain as expected or throw a more detailed error as to why its not authenticated.

```
let server = vertx.createServer(blahBlah);
server.connectionHandler(c => console.log(c.peerCertificateChain()));
```

The example code above gives me an 'Unhandled exception caused by peer not authenticated'
```
at sun.security.ssl.SSLSessionImpl.getPeerCertificateChain(SSLSessionImpl.java:501)
at io.vertx.core.net.impl.ConnectionBase.peerCertificateChain(ConnectionBase.java:471)

```

I believe the certs to be fine/valid so I'm curious as to why I'm receiving this stacktrace

**Comment by UglyHobbitFeet** [comment]
Closing for now as I am getting the same error in the java vertx version
