### ISSUE TITLE
 to create the vert.x instance caused by java.lang.IllegalStateException: No ClusterManagerFactory instances found on classpath

### ISSUE THREAD

**Issue by yuangu** [reactiverse/es4x#329]
learn it    step by  step .but ``` node_modules\.bin\es4x-launcher.cmd  --cluster```

error:
```
[1m[34mStarting clustering...[0m
[1m[34mNo cluster-host specified so using address 127.0.0.1[0m
[1m[33mES4X is using graaljs in interpreted mode! Add the JVMCI compiler module in order to run in optimal mode![0m
[0m[31mFailed to create the vert.x instance caused by java.lang.IllegalStateException: No ClusterManagerFactory instances found on classpath
        at io.vertx.core.impl.VertxImpl.getClusterManager(VertxImpl.java:485)
        at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:172)
        at io.vertx.core.impl.VertxImpl.clusteredVertx(VertxImpl.java:98)
        at io.vertx.core.impl.VertxFactoryImpl.clusteredVertx(VertxFactoryImpl.java:52)
        at io.vertx.core.impl.VertxFactoryImpl.clusteredVertx(VertxFactoryImpl.java:45)
        at io.vertx.core.Vertx.clusteredVertx(Vertx.java:97)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.create(ClasspathHandler.java:132)
        at io.vertx.core.impl.launcher.commands.BareCommand.startVertx(BareCommand.java:257)
        at io.vertx.core.impl.launcher.commands.BareCommand.run(BareCommand.java:192)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:249)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
        at io.reactiverse.es4x.ES4X.main(ES4X.java:72)
[1m[31mTimed out in starting clustered Vert.x[0m
```

**Comment by yuangu** [comment]
I solved it. chinese peple。This is my tutorial in chinese。may be it's can help your that same problem as mine.
https://my.oschina.net/jjyuangu/blog/3229807

**Comment by pmlopes** [comment]
@yuangu you can simplify this by adding to your `package.json`:

```js
{
  "dependencies" : [
    "io.vertx:vertx-hazelcast:3.9.0"
  ]
}
```

You can add any jvm dependency that isn't on npm. In this case it pull the hazelcast cluster manager and it will be available to the application at runtime. So clustering will work.

I must say clustering isn't fully tested yet so you might find bugs. If you do, please report them :+1:
