### ISSUE TITLE
clean start causes error

### ISSUE THREAD

**Issue by Dutchboy** [reactiverse/es4x#33]
Following the initial clean start, it doesn't work.

mkdir my-app
cd my-app
npm init -y
npm add vertx-scripts --save-dev
npm add @vertx/unit --save-dev
npm add @vertx/core --save-prod
npm add @vertx/web --save-prod

I created the provided index.js / index.test.js

(you forgot to warn about doing a "vertx-scripts init" (for the pom file to be produced / overwritten)

I myself did a global npm install of vertx-scripts, because it would otherwise not recognize it as a command (Windows!)

The error produced was:

```
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>#88:17<eval>:3:0 Expected an operand but found import
import { Router } from '@vertx/web';
```

How to solve this?

**Comment by pmlopes** [comment]
@Dutchboy could you tell me how did you run this to get that message? And what java version is in your system? `java -version` output

**Comment by Dutchboy** [comment]
in the mean time, I also did some on my Ubuntu machine....
java -version output is:

Win:
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
Ubuntu:
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

On Ubuntu, I've got a different error message:
```
src/main/resources/io/reactiverse/es4x/jvm-npm.js:121 SyntaxError: index.js:14:11 Expected : but found app
    return app.accept(result);
```
(with a long list of all the same..... ;-)

**Comment by Dutchboy** [comment]
Windows:
I have just updated to JDK 10.0.0.2 - still another error:
`
λ npm start                                                                                                                                                                                                            
                                                                                                                                                                                                                       
> vertx_npm@1.0.0 start C:\00.Dev\1000.Sandbox\vertx_npm                                                                                                                                                               
> vertx-scripts launcher run                                                                                                                                                                                           
                                                                                                                                                                                                                       
Running: java ... index.js                                                                                                                                                                                             
WARNING: An illegal reflective access operation has occurred                                                                                                                                                           
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/C:/Users/Krenning/.m2/repository/io/netty/netty-common/4.1.19.Final/netty-common-4.1.19.Final.jar) to constructor java.nio.DirectByt
eBuffer(long,int)                                                                                                                                                                                                      
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil                                                                                                                    
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations                                                                                                                  
WARNING: All illegal access operations will be denied in a future release                                                                                                                                              
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1                                                                                                                                         
\                                                                                                                                                                                                                      
        at java.base/java.util.regex.Pattern.error(Unknown Source)                                                                                                                                                     
        at java.base/java.util.regex.Pattern.compile(Unknown Source)                                                                                                                                                   
        at java.base/java.util.regex.Pattern.<init>(Unknown Source)                                                                                                                                                    
        at java.base/java.util.regex.Pattern.compile(Unknown Source)                                                                                                                                                   
        at java.base/java.lang.String.replaceAll(Unknown Source)                                                                                                                                                       
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$59$5166A$jvm_npm$cu1$restOf.L:17#parsePaths(src/main/resources/io/reactiverse/es4x/jvm-npm.js:201)                          
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$57$5600$jvm_npm$cu1$restOf.:scopeCall-3(src/main/resources/io/reactiverse/es4x/jvm-npm.js)                                  
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$57$5600$jvm_npm$cu1$restOf.L:17#paths(src/main/resources/io/reactiverse/es4x/jvm-npm.js:214)                                
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$55$5005A$jvm_npm.L:17#findRoots(src/main/resources/io/reactiverse/es4x/jvm-npm.js:182)                                      
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$54$4386AA$jvm_npm.L:17#resolve(src/main/resources/io/reactiverse/es4x/jvm-npm.js:155)                                       
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$53$3940AA$jvm_npm.L:17#Require(src/main/resources/io/reactiverse/es4x/jvm-npm.js:139)                                       
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(Unknown Source)                                                                                                                
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(Unknown Source)                                                                                                                    
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(Unknown Source)                                                                                                                      
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(Unknown Source)                                                                                                                     
        at io.reactiverse.es4x.impl.nashorn.NashornLoader.require(NashornLoader.java:91)                                                                                                                               
        at io.reactiverse.es4x.impl.nashorn.NashornLoader.main(NashornLoader.java:101)                                                                                                                                 
        at io.reactiverse.es4x.VerticleFactory$1.start(VerticleFactory.java:103)                                                                                                                                       
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)                                                                                                                          
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)                                                                                                                                      
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)                                                                                                                  
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)                                                                                                          
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)                                                                                                                                                
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)                                                                                                                
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                                       
        at java.base/java.lang.Thread.run(Unknown Source)                                                                                                                                                              
Failed in deploying verticle java.util.regex.PatternSyntaxException: Unexpected internal error near index 1                                                                                                            
\                                                                                                                                                                                                                      
        at java.base/java.util.regex.Pattern.error(Unknown Source)                                                                                                                                                     
        at java.base/java.util.regex.Pattern.compile(Unknown Source)                                                                                                                                                   
        at java.base/java.util.regex.Pattern.<init>(Unknown Source)                                                                                                                                                    
        at java.base/java.util.regex.Pattern.compile(Unknown Source)                                                                                                                                                   
        at java.base/java.lang.String.replaceAll(Unknown Source)                                                                                                                                                       
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$59$5166A$jvm_npm$cu1$restOf.L:17#parsePaths(src/main/resources/io/reactiverse/es4x/jvm-npm.js:201)                          
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$57$5600$jvm_npm$cu1$restOf.:scopeCall-3(src/main/resources/io/reactiverse/es4x/jvm-npm.js)                                  
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$57$5600$jvm_npm$cu1$restOf.L:17#paths(src/main/resources/io/reactiverse/es4x/jvm-npm.js:214)                                
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$55$5005A$jvm_npm.L:17#findRoots(src/main/resources/io/reactiverse/es4x/jvm-npm.js:182)                                      
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$54$4386AA$jvm_npm.L:17#resolve(src/main/resources/io/reactiverse/es4x/jvm-npm.js:155)                                       
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$53$3940AA$jvm_npm.L:17#Require(src/main/resources/io/reactiverse/es4x/jvm-npm.js:139)                                       
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(Unknown Source)                                                                                                                
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(Unknown Source)                                                                                                                    
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(Unknown Source)                                                                                                                      
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(Unknown Source)                                                                                                                     
        at io.reactiverse.es4x.impl.nashorn.NashornLoader.require(NashornLoader.java:91)                                                                                                                               
        at io.reactiverse.es4x.impl.nashorn.NashornLoader.main(NashornLoader.java:101)                                                                                                                                 
        at io.reactiverse.es4x.VerticleFactory$1.start(VerticleFactory.java:103)                                                                                                                                       
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)                                                                                                                          
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)                                                                                                                                      
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)                                                                                                                  
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)                                                                                                          
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)                                                                                                                                                
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)                                                                                                                
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                                       
        at java.base/java.lang.Thread.run(Unknown Source)                                                                                                                                                              
                                                                                                                                                                                                                       
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1                                                                                                                                         
\                                                                                                                                                                                                                      
        at java.base/java.util.regex.Pattern.error(Unknown Source)                                                                                                                                                     
        at java.base/java.util.regex.Pattern.compile(Unknown Source)                                                                                                                                                   
        at java.base/java.util.regex.Pattern.<init>(Unknown Source)                                                                                                                                                    
        at java.base/java.util.regex.Pattern.compile(Unknown Source)                                                                                                                                                   
        at java.base/java.lang.String.replaceAll(Unknown Source)                                                                                                                                                       
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$59$5166A$jvm_npm$cu1$restOf.L:17#parsePaths(src/main/resources/io/reactiverse/es4x/jvm-npm.js:201)                          
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$57$5600$jvm_npm$cu1$restOf.:scopeCall-3(src/main/resources/io/reactiverse/es4x/jvm-npm.js)                                  
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$57$5600$jvm_npm$cu1$restOf.L:17#paths(src/main/resources/io/reactiverse/es4x/jvm-npm.js:214)                                
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$55$5005A$jvm_npm.L:17#findRoots(src/main/resources/io/reactiverse/es4x/jvm-npm.js:182)                                      
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$54$4386AA$jvm_npm.L:17#resolve(src/main/resources/io/reactiverse/es4x/jvm-npm.js:155)                                       
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$53$3940AA$jvm_npm.L:17#Require(src/main/resources/io/reactiverse/es4x/jvm-npm.js:139)                                       
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(Unknown Source)                                                                                                                
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(Unknown Source)                                                                                                                    
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(Unknown Source)                                                                                                                      
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(Unknown Source)                                                                                                                     
        at io.reactiverse.es4x.impl.nashorn.NashornLoader.require(NashornLoader.java:91)                                                                                                                               
        at io.reactiverse.es4x.impl.nashorn.NashornLoader.main(NashornLoader.java:101)                                                                                                                                 
        at io.reactiverse.es4x.VerticleFactory$1.start(VerticleFactory.java:103)                                                                                                                                       
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)                                                                                                                          
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)                                                                                                                                      
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)                                                                                                                  
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)                                                                                                          
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)                                                                                                                                                
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)                                                                                                                
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                                       
        at java.base/java.lang.Thread.run(Unknown Source)                                                                                                                                                              
                                                                                                                                                                                                                       `

**Comment by pmlopes** [comment]
@Dutchboy I believe you used the `index.js` from the [docs](docs/). Sadly with Java8 (Nashorn only supports ES5.1 so no arrows expressions:

```js
/// <reference types="@vertx/core/runtime" />
// @ts-check
import { Router } from '@vertx/web';

const app = Router.router(vertx);

app.route().handler(function (ctx) {
  ctx.response().end('Hello from Vert.x Web!');
});

vertx.createHttpServer()
  .requestHandler((result) => {
    return app.accept(result);
  } )
  .listen(8080);
```

This should be:

```js
/// <reference types="@vertx/core/runtime" />
// @ts-check
import { Router } from '@vertx/web';

const app = Router.router(vertx);

app.route().handler(function (ctx) {
  ctx.response().end('Hello from Vert.x Web!');
});

vertx.createHttpServer()
  .requestHandler(function (result) {
    return app.accept(result);
  } )
  .listen(8080);
```

I works with java >=9 although with 11 you'll see an extra warning:

```
Warning: Nashorn engine is planned to be removed from a future JDK release
```

**Comment by pmlopes** [comment]
The regular expression issue you're seeing seems to be something else. Internally ES4X will translate ES6 module require syntax to commonjs and probably your code/bundle generates a format that I can't really parse. It would be nice if you could provide a reproducer, so I could see how to fix the regular expression.

**Comment by pmlopes** [comment]
The regex issue is windows specific:

https://github.com/reactiverse/es4x/blob/develop/src/main/resources/io/reactiverse/es4x/jvm-npm.js#L201

I need to automate testing on Windows :(

It's a broken regex...

**Comment by Dutchboy** [comment]
Mean while I updates the jdk to version 10.... With regards the regex, true.... this causes the latter problem....

**Comment by Dutchboy** [comment]
What about changing the 

https://github.com/reactiverse/es4x/blob/develop/src/main/resources/io/reactiverse/es4x/jvm-npm.js#L201

paths = paths.replaceAll('\\', '/');
with
paths = paths.replaceAll(/\134/g,"/");
(( source https://bytes.com/topic/javascript/answers/580915-replacing-backslash-forward-slash-javascript ))

**Comment by pmlopes** [comment]
@Dutchboy that is the idea, but I need to verify a few things extra, the `paths` object seems to be a `java` string and in that case replace is different. If nashorn and graalvm will convert it always to Ms string then the above solution seems enough.
