### ISSUE TITLE
Vertx Composite Futures not working: Multi threading issue

### ISSUE THREAD

**Issue by Dylancorbus** [reactiverse/es4x#336]
## Unhandled Error caused by java.lang.IllegalStateException: Multi threaded access requested by thread Thread[vert.x-eventloop-thread-2,5,main] but is not allowed for language(s) js.
I am trying to make a skeleton for the API I'm going to build, I have a Redis cache and a MongoDB I need to connect to and read from concurrently, I'm using vertx futures to execute the reads to mongo and Redis and using composite future to asynchronously process the result when both are complete.

Here is my typescript code:

```ts
import { AsyncResult, Message, Future, CompositeFuture } from '@vertx/core';
import { Redis, RedisAPI, Response, RedisConnection } from '@vertx/redis-client';
import { MongoClient } from '@vertx/mongo-client';
let deploymentId = '';
const eb = vertx.eventBus();

const mongoConfig = {
    connection_string: 'mongodb://localhost:27017/Users'
};
const mongoClient = MongoClient.createShared(vertx, mongoConfig);

const redis = Redis.createClient(vertx, 'redis://localhost:6379').connect((res: AsyncResult<RedisConnection>) => {
    if (res.succeeded()) {
        console.log(res.result());
    } else {
        console.log(vertx.deploymentIDs());
        vertx.undeploy(deploymentId);
        console.log('connection failed' + res.cause().getMessage());
    }
});

const redisClient = RedisAPI.api(redis);

const matcher = (msg: Message<any>): void => {
    console.log('REQUEST');
    const val = JSON.parse(msg.body());
    let redisFuture = Future.future((promise: any) => {
        redisClient.get('test', (redisRes: AsyncResult<Response>) => {
            if (redisRes.succeeded()) {
                redisClient.set(['test', val.amount], promise);
            }
        });
    });

    let mongoFuture = Future.future((promise: any) => {
        mongoClient.findOne('users', { email: val.email }, {}, promise);
    });

    CompositeFuture.all(redisFuture, mongoFuture).onComplete((ar: AsyncResult<CompositeFuture>) => {
        if (ar.succeeded()) {
            //perform lots of logic
            let reply = {
                mongo: ar.result().resultAt(1), 
                redis: ar.result().resultAt(0).toString()
            }
            //reply with result /not implemented yet
            msg.reply(JSON.stringify(reply));
        
        } else {
            console.log(ar.cause());
            msg.reply(ar.cause());
        }
        });
}

const setDeploymentId = (msg: Message<string>): void => {
    console.log('set deployid to ' + msg.body());
    deploymentId = msg.body();
}

eb.consumer('/matchHandler', matcher);
eb.consumer('/deploymentId', setDeploymentId);
```

```sh
Unhandled Error caused by java.lang.IllegalStateException: Multi threaded access requested by thread Thread[vert.x-eventloop-thread-2,5,main] but is not allowed for language(s) js.
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:639)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.checkAllThreadAccesses(PolyglotContextImpl.java:542)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:469)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.enter(PolyglotEngineImpl.java:1518)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:86)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:403)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:330)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:320)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.FunctionProxyHandler.invoke(HostInteropReflect.java:454)
        at com.sun.proxy.$Proxy44.handle(Unknown Source)
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:176)
        at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21)
        at io.vertx.redis.client.Redis.lambda$null$0(Redis.java:105)
        at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:105)
        at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:150)
        at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
        at io.vertx.redis.client.impl.RedisConnectionImpl.lambda$handle$6(RedisConnectionImpl.java:290)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

When i change the code to this it works no problem but i want to get the results concurrently not sequentially:
```ts
import { AsyncResult, Message, Future, CompositeFuture } from '@vertx/core';
import { Redis, RedisAPI, Response, RedisConnection } from '@vertx/redis-client';
import { MongoClient } from '@vertx/mongo-client';
let deploymentId = '';
const eb = vertx.eventBus();

const mongoConfig = {
    connection_string: 'mongodb://localhost:27017/Users'
};
const mongoClient = MongoClient.createShared(vertx, mongoConfig);

const redis = Redis.createClient(vertx, 'redis://localhost:6379').connect((res: AsyncResult<RedisConnection>) => {
    if (res.succeeded()) {
        console.log(res.result());
    } else {
        console.log(vertx.deploymentIDs());
        vertx.undeploy(deploymentId);
        console.log('connection failed' + res.cause().getMessage());
    }
});

const redisClient = RedisAPI.api(redis);

const matcher = (msg: Message<any>): void => {
    console.log('REQUEST' + msg.body());
    redisClient.get('test', (redisRes: AsyncResult<Response>) => {
        if (redisRes.succeeded()) {
            const val = JSON.parse(msg.body());
            redisClient.set(['test', val.amount],
                (handler: AsyncResult<Response>) => {
                    if (handler.succeeded()) {
                        console.log(handler.result());
                        mongoClient.findOne('users', { email: 'dylancorbus@gmail.com' }, {}, (res: AsyncResult<any>) => {
                            if (res.succeeded()) {
                                console.log(res.result());
                                let reply = {
                                    mongo: res.result(),
                                    redis: redisRes.result().toString()
                                }
                                msg.reply(JSON.stringify(reply));
                            } else {
                                console.log(res.cause());
                            }
                        });
                    } else {
                        console.log(handler.cause());
                    }
                });
        }
    });
}

const setDeploymentId = (msg: Message<string>): void => {
    console.log('set deployid to ' + msg.body());
    deploymentId = msg.body();
}

eb.consumer('/matchHandler', matcher);
eb.consumer('/deploymentId', setDeploymentId);
```

package.json

```json
{
  "version": "1.0.0",
  "description": "Spotback Matching-Service.",
  "main": "build/lib/server.js",
  "scripts": {
    "postinstall": "es4x install -f",
    "prestart": "tsc",
    "test": "es4x test index.test.js",
    "start": "export CONF_ENC_UNLOCK=<some_password> && es4x run --conf $(node build/decrypt.js) --redeploy \"*.ts\" --on-redeploy \"npm run start\" build/lib/server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "name": "matching-service",
  "devDependencies": {
    "@vertx/unit": "^3.9.0",
    "typescript": "latest",
    "es4x-pm": "latest"
  },
  "dependencies": {
    "@types/node": "^13.11.1",
    "@vertx/core": "^3.9.0",
    "@vertx/mongo-client": "^3.9.0",
    "@vertx/redis-client": "^3.9.0",
    "@vertx/web": "latest",
    "secure-env": "^1.2.0"
  }
}
```

**Comment by Dylancorbus** [comment]
Changed the code around and this is working
```ts
const matcher = (msg: Message<any>): void => {
    console.log('REQUEST' + msg.body());
    const val = JSON.parse(msg.body());
    let redisFuture = Future.future((promise: any) => {
        redisClient.get('test', promise);
    });

    let mongoFuture = Future.future((promise: any) => {
        mongoClient.findOne('users', { email: val.email }, {}, promise);
    });

    CompositeFuture.all(redisFuture, mongoFuture).onComplete((ar: AsyncResult<CompositeFuture>) => {
        if (ar.succeeded()) {
            //perform lots of logic
            let reply = {
                mongo: ar.result().resultAt(1),
                redis: ar.result().resultAt(0).toString()
            }
            //reply with result /not implemented yet
            msg.reply(JSON.stringify(reply));
            redisClient.set(['test', val.amount], (res: AsyncResult<Response>) => {

            });
        } else {
            console.log(ar.cause());
            msg.reply(ar.cause());
        }
    });
}
```
looking at the origin code that had the problem it looks like there was a problem connecting to redis in the handler for the redis read, i assume this is done on a worker thread?

**Comment by yuangu** [comment]
The same problem. @Dylancorbus How do you solve this?

`function getDefaultServer()
: JDBCClient {
    let  jdbcClient: JDBCClient = JDBCClient.createShared(vertx, {
        "url": "jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false",
        "driver_class": "com.mysql.cj.jdbc.Driver",
        "max_pool_size": 30,
        "user": "root",
        "password": "123456"
    })
return jdbcClient;
}

function getConnection(jdbcClient: JDBCClient)
: Future<SQLConnection> {
  let promise: Promise<SQLConnection> = Promise.promise()
 
  jdbcClient.getConnection((res: AsyncResult<SQLConnection>) => {
      if (res.failed()) {
          res.cause().printStackTrace()
          promise.fail(res.cause())
          return;
      }

      promise.complete(res.result())
  })
  return promise.future()
}

let jdbcClient = getDefaultServer()

getConnection(jdbcClient).onFailure((res: Throwable) => {
  console.log('执行失败', res.getMessage())
}).onSuccess((res: SQLConnection) => {
   console.log("执行成功")
})
`

**Comment by Dylancorbus** [comment]
@yuangu first off I, had to switch away from typescript to javascript, Paulo Lopes talks about it here https://gitter.im/es4x/Lobby?at=5d7a6d8b0fc49226624ed59d#, and second I'm having issues when I try to do more than one i/o operation on the same DB client or Redis client.

# This code has that multi-threaded problem:
```js
const mongoClient = MongoClient.createShared(vertx, mongoConfig);

const redis = Redis.createClient(vertx, `redis://${redisHost}:6379`).connect((res) => {
    if (res.succeeded()) {
        console.log(Constants.REDIS_CONNECT_SUCCESS + res.result());
    } else {
        console.log(vertx.deploymentIDs());
        vertx.undeploy(deploymentId);
        console.log(Constants.REDIS_CONNECT_FAILED + res.cause().getMessage());
    }
});
const redisClient = RedisAPI.api(redis);

const matcher = (msg) => {
    console.log(Constants.MATCH_REQ_LOG);
    const val = JSON.parse(msg.body());
    let redisFuture = Future.future((promise) => {
        redisClient.scan(['0'], promise);
    });

    let mongoFuture = Future.future((promise) => {
        mongoClient.findOne('users', { email: val.email }, {}, promise);
    });

    let mongoFuture2 = Future.future((promise) => {
        mongoClient.findOne('users', { email: val.email }, {}, promise);
    });

    CompositeFuture.all(redisFuture, mongoFuture, mongoFuture2).onComplete((ar) => {
        if (ar.succeeded()) {
            //perform lots of logic
            let reply = {
                mongo: ar.result().resultAt(1),
                redis: ar.result().resultAt(0).toString()
            }
            //reply with result /not implemented yet
            msg.reply(JSON.stringify(reply));
            redisClient.set(['test', val.amount], (res) => {

            });
        } else {
            console.log(ar.cause());
            msg.reply(ar.cause());
        }
    });
}
```

# Exception thrown:
```
Callback onResult call produced an error caused by java.lang.IllegalStateException: Multi threaded access requested by thread Thread[async-channel-group-0-handler-executor,5,main] but is not allowed for language(s) js.
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:639)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.checkAllThreadAccesses(PolyglotContextImpl.java:542)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:469)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.enter(PolyglotEngineImpl.java:1518)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:86)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:474)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:449)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:419)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:403)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:330)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:320)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotMap.entrySet(PolyglotMap.java:117)
        at io.vertx.core.json.JsonObject.iterator(JsonObject.java:855)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:119)
        at io.vertx.ext.mongo.impl.codec.json.JsonObjectCodec.forEach(JsonObjectCodec.java:23)
        at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.writeDocument(AbstractJsonCodec.java:258)
        at io.vertx.ext.mongo.impl.codec.json.AbstractJsonCodec.encode(AbstractJsonCodec.java:28)
        at org.bson.BsonDocumentWrapper.getUnwrapped(BsonDocumentWrapper.java:195)
        at org.bson.BsonDocumentWrapper.isEmpty(BsonDocumentWrapper.java:115)
        at com.mongodb.operation.DocumentHelper.putIfNotNullOrEmpty(DocumentHelper.java:43)
        at com.mongodb.operation.FindOperation.getCommand(FindOperation.java:1001)
        at com.mongodb.operation.FindOperation.access$200(FindOperation.java:84)
        at com.mongodb.operation.FindOperation$2$1.call(FindOperation.java:751)
        at com.mongodb.operation.OperationHelper$5.call(OperationHelper.java:238)
        at com.mongodb.operation.OperationHelper.validateCollation(OperationHelper.java:137)
        at com.mongodb.operation.OperationHelper$4.call(OperationHelper.java:226)
        at com.mongodb.operation.OperationHelper.validateReadConcern(OperationHelper.java:96)
        at com.mongodb.operation.OperationHelper.validateReadConcernAndCollation(OperationHelper.java:220)
        at com.mongodb.operation.OperationHelper.validateReadConcernAndCollation(OperationHelper.java:235)
        at com.mongodb.operation.FindOperation$2.call(FindOperation.java:742)
        at com.mongodb.operation.OperationHelper$7.onResult(OperationHelper.java:517)
        at com.mongodb.operation.OperationHelper$7.onResult(OperationHelper.java:514)
        at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:109)
        at com.mongodb.internal.connection.DefaultServer$1.onResult(DefaultServer.java:98)
        at com.mongodb.internal.async.ErrorHandlingResultCallback.onResult(ErrorHandlingResultCallback.java:49)
        at com.mongodb.internal.connection.DefaultConnectionPool$2.onResult(DefaultConnectionPool.java:213)
        at com.mongodb.internal.connection.DefaultConnectionPool$2.onResult(DefaultConnectionPool.java:198)
        at com.mongodb.internal.connection.UsageTrackingInternalConnection$1.onResult(UsageTrackingInternalConnection.java:65)
        at com.mongodb.internal.connection.UsageTrackingInternalConnection$1.onResult(UsageTrackingInternalConnection.java:57)
        at com.mongodb.internal.connection.InternalStreamConnection$1$1.onResult(InternalStreamConnection.java:166)
        at com.mongodb.internal.connection.InternalStreamConnection$1$1.onResult(InternalStreamConnection.java:153)
        at com.mongodb.internal.connection.InternalStreamConnectionInitializer$3.onResult(InternalStreamConnectionInitializer.java:215)
        at com.mongodb.internal.connection.InternalStreamConnectionInitializer$3.onResult(InternalStreamConnectionInitializer.java:209)
        at com.mongodb.internal.connection.CommandHelper$1.onResult(CommandHelper.java:59)
        at com.mongodb.internal.connection.CommandHelper$1.onResult(CommandHelper.java:53)
        at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:395)
        at com.mongodb.internal.connection.InternalStreamConnection$2$1.onResult(InternalStreamConnection.java:372)
        at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:667)
        at com.mongodb.internal.connection.InternalStreamConnection$MessageHeaderCallback$MessageCallback.onResult(InternalStreamConnection.java:634)
        at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:510)
        at com.mongodb.internal.connection.InternalStreamConnection$5.completed(InternalStreamConnection.java:507)
        at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:220)
        at com.mongodb.internal.connection.AsynchronousChannelStream$BasicCompletionHandler.completed(AsynchronousChannelStream.java:203)
        at com.mongodb.internal.connection.tlschannel.async.AsynchronousTlsChannel$3$1.run(AsynchronousTlsChannel.java:151)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

# This code works fine:
```js
const mongoClient = MongoClient.createShared(vertx, mongoConfig);
const mongoClient2 = MongoClient.createShared(vertx, mongoConfig);

const redis = Redis.createClient(vertx, `redis://${redisHost}:6379`).connect((res) => {
    if (res.succeeded()) {
        console.log(Constants.REDIS_CONNECT_SUCCESS + res.result());
    } else {
        console.log(vertx.deploymentIDs());
        vertx.undeploy(deploymentId);
        console.log(Constants.REDIS_CONNECT_FAILED + res.cause().getMessage());
    }
});
const redisClient = RedisAPI.api(redis);

const matcher = (msg) => {
    console.log(Constants.MATCH_REQ_LOG);
    const val = JSON.parse(msg.body());
    let redisFuture = Future.future((promise) => {
        redisClient.scan(['0'], promise);
    });

    let mongoFuture = Future.future((promise) => {
        mongoClient.findOne('users', { email: val.email }, {}, promise);
    });

    let mongoFuture2 = Future.future((promise) => {
        mongoClient2.findOne('users', { email: val.email }, {}, promise);
    });

    CompositeFuture.all(redisFuture, mongoFuture, mongoFuture2).onComplete((ar) => {
        if (ar.succeeded()) {
            //perform lots of logic
            let reply = {
                mongo: ar.result().resultAt(1),
                redis: ar.result().resultAt(0).toString()
            }
            //reply with result /not implemented yet
            msg.reply(JSON.stringify(reply));
            redisClient.set(['test', val.amount], (res) => {

            });
        } else {
            console.log(ar.cause());
            msg.reply(ar.cause());
        }
    });
}
```

Looks like the problem is that you cant use the same object to perform more than 1 i/o operation at the same time. When I create 2 objects mongoClient and mongoClient2 this problem goes away but this not good.

**Comment by pmlopes** [comment]
This is a limitation of graaljs, if this kind of errors occurs we need to address them upstream as it signals that the thread context is not being properly set.
