### ISSUE TITLE
React SSR Example (in TS though): ModuleError: Module "stream" was not found

### ISSUE THREAD

**Issue by LouisStAmour** [reactiverse/es4x#359]
Excited by the prospect of using Server-Side-React on the JVM, I gave it a go, but ran into an issue. Any tips or pointers?

My current code is at https://github.com/LouisStAmour/es4x-react-ssr-typescript-demo

The `tsc` for this repo passes if I use:

```typescript
export interface AsyncResult<T> extends PromiseLike<T> {
  succeeded() : boolean;
  failed() : boolean;
  cause() : Throwable | null;
  result() : T | null;
}
```

in node_modules/@vertx/core/index.d.ts

However, running `yarn start` fails with:

```log
ModuleError: Module "stream" was not found
        at <js> Require.resolve(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:165:5324-5402)
        at <js> Require(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:132:4365-4391)
        at <js> this.require(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
        at <js> :anonymous(node_modules/react-dom/cjs/react-dom-server.node.development.js:21:554-570)
        at <js> :anonymous(node_modules/react-dom/cjs/react-dom-server.node.development.js:15-4084:383-130146)
        at <js> _load(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
        at <js> Require(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
        at <js> this.require(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
        at <js> :anonymous(node_modules/react-dom/server.node.js:6:227-279)
        at <js> _load(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
        at <js> Require(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
        at <js> this.require(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
        at <js> :anonymous(node_modules/react-dom/server.js:3:94-117)
        at <js> _load(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
        at <js> Require(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:141:4628-4652)
        at <js> this.require(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:46:1459-1475)
        at <js> :anonymous(out/index.js:6:258-284)
        at <js> _load(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:97:3264-3345)
        at <js> runMain(file:node_modules/.lib/es4x-0.12.0.jar!/io/reactiverse/es4x/jvm-npm.js:110:3648-3692)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:549)
        at io.reactiverse.es4x.impl.JSVerticleFactory$1.start(JSVerticleFactory.java:81)
        at io.vertx.core.Verticle.start(Verticle.java:66)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Near as I can tell, this because of lines like https://github.com/facebook/react/blob/df14b5bcc163516fc0f1ad35e9b93732c66c1085/packages/react-dom/src/server/ReactDOMNodeStreamRenderer.js#L9 which have been around for 3 years... how can I get the React SSR demo to work?

**Comment by pmlopes** [comment]
stream is a node native module. It requires a polyfill or change the build to assume that you are on a browser not node.

**Comment by LouisStAmour** [comment]
I see. I had made an assumption that because GraalJS included node components that it had included “stream” also, and that I’d done something wrong in my configuration of the React SSR example that broke the use of the Node module.

In the example, however, the server is compiled using webpack - in examples/react-ssr-basic/webpack.config.js - and Webpack by default prefers “browser” imports, where react-dom sets a server browser import in package.json of server.browser.js

In my version I was loading server.node.js because I wasn’t using webpack to bundle browser-specific code for the server to run.

Okay, makes sense.
