### ISSUE TITLE
Classpath error

### ISSUE THREAD

**Issue by stephenh** [reactiverse/es4x#39]
Hi, I'm getting this run when trying to run a graal script in es4x:

```
TypeError: Access to host class io.vertx.ext.web.handler.BasicAuthHandler is not allowed or does not exist.
        at <js> :anonymous(/home/stephen/company/app/node_modules/@vertx/web/index.js:3:137-190)
        at <js> _load(src/main/resources/io/reactiverse/es4x/jvm-npm.js:126:3641-3722)
        at <js> Require(src/main/resources/io/reactiverse/es4x/jvm-npm.js:148:4250-4274)
        at <js> this.require(src/main/resources/io/reactiverse/es4x/jvm-npm.js:99:2911-2927)
        at <js> :anonymous(vertx.js:9:219-239)
        at <js> _load(src/main/resources/io/reactiverse/es4x/jvm-npm.js:126:3641-3722)
        at <js> Require(src/main/resources/io/reactiverse/es4x/jvm-npm.js:148:4250-4274)
        at org.graalvm.polyglot.Value.execute(Value.java:312)
        at io.reactiverse.es4x.impl.graal.GraalLoader.require(GraalLoader.java:129)
        at io.reactiverse.es4x.impl.graal.GraalLoader.main(GraalLoader.java:139)
        at io.reactiverse.es4x.impl.graal.GraalLoader.main(GraalLoader.java:31)
        at io.reactiverse.es4x.VerticleFactory$1.start(VerticleFactory.java:103)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

I'm pretty sure I've ran the incantation correctly, e.g. per other issue I've `cd`'d into the `build` directory, ran `../node_modules/.bin/vertx-scripts init` and `package` to create the mvn/pom.xml files (that now existing within the `build/` directory itself).

I also grabbed a quick snapshot of the classpath:

```
stephen  22379  0.0  0.1 6830392 26180 pts/2   Sl+  08:09   0:00 java -cp /home/stephen/.m2/repository/io/vertx/vertx-core/3.5.4/vertx-core-3.5.4.jar:/home/stephen/.m2/repository/io/netty/netty-transport/4.1.19.Final/netty-transport-4.1.19.Final.jar:/home/stephen/.m2/repository/io/netty/netty-codec-http/4.1.19.Final/netty-codec-http-4.1.19.Final.jar:/home/stephen/.m2/repository/io/netty/netty-buffer/4.1.19.Final/netty-buffer-4.1.19.Final.jar:/home/stephen/.m2/repository/io/netty/netty-codec-dns/4.1.19.Final/netty-codec-dns-4.1.19.Final.jar:/home/stephen/.m2/repository/io/netty/netty-codec/4.1.19.Final/netty-codec-4.1.19.Final.jar:/home/stephen/.m2/repository/io/netty/netty-codec-socks/4.1.19.Final/netty-codec-socks-4.1.19.Final.jar:/home/stephen/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar:/home/stephen/.m2/repository/io/netty/netty-codec-http2/4.1.19.Final/netty-codec-http2-4.1.19.Final.jar:/home/stephen/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/home/stephen/.m2/repository/io/netty/netty-common/4.1.19.Final/netty-common-4.1.19.Final.jar:/home/stephen/.m2/repository/io/netty/netty-handler/4.1.19.Final/netty-handler-4.1.19.Final.jar:/home/stephen/.m2/repository/io/netty/netty-resolver-dns/4.1.19.Final/netty-resolver-dns-4.1.19.Final.jar:/home/stephen/.m2/repository/io/reactiverse/es4x/0.5.4/es4x-0.5.4.jar:/home/stephen/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar:/home/stephen/.m2/repository/io/netty/netty-resolver/4.1.19.Final/netty-resolver-4.1.19.Final.jar:/home/stephen/.m2/repository/io/netty/netty-handler-proxy/4.1.19.Final/netty-handler-proxy-4.1.19.Final.jar:/home/stephen/company/app/build/target/classes io.vertx.core.Launcher run vertx.js
```

Hm. I see `vertx-core` on there but not `vertx-web`...I have both in my `package.json`:

```
$ cat package.json | grep vertx
    "@vertx/core": "^3.5.3",
    "@vertx/web": "^3.5.3",
    "vertx-scripts": "^1.1.4"
```

And have done `yarn install`/etc. Do you have any ideas?

**Comment by pmlopes** [comment]
behind the scenes the `vertx-scripts` (now renamed to `es4x-cli` for the future releases) invokes maven to generate the classpath and this gets stored in `target/classpath.txt`. This file should contain 1 line with the classpath, and when we run, the script reads the first line of the file.

Could it be that maven is caching this file?, if you `rm -Rf target` or `mvn clean` and do again `npm install` will it work? Sadly there's no clean target in `npm` so we cannot bind the action to invoke maven clean too...

**Comment by stephenh** [comment]
Ah, got it, yep, it sounds like my `target/classpath.txt` got out of sync. Not sure what happened, but I moved over to `es4x-cli` and after doing `yarn install` I see that `es4x postinstall` ran automatically and `target/classpath.txt` has the latest/great jars listed. I'll close this out as not reproducible. Thanks!
