### ISSUE TITLE
Failed start vert.x 4.0.0

### ISSUE THREAD

**Issue by daihy8759** [reactiverse/es4x#474]
```java
Failed to deploy verticle js:dist/index.js caused by java.lang.AbstractMethodError: Method io/reactiverse/es4x/impl/JSVerticleFactory.createVerticle(Ljava/lang/String;Ljava/lang/ClassLoader;Lio/vertx/core/Promise;)V is abstract
	at io.reactiverse.es4x.impl.JSVerticleFactory.createVerticle(JSVerticleFactory.java)
	at io.vertx.core.impl.VerticleManager.doDeployVerticle(VerticleManager.java:217)
	at io.vertx.core.impl.VerticleManager.doDeployVerticle(VerticleManager.java:193)
	at io.vertx.core.impl.VerticleManager.doDeployVerticle(VerticleManager.java:180)
	at io.vertx.core.impl.VerticleManager.deployVerticle(VerticleManager.java:156)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:616)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:622)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:168)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:403)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:248)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:402)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.reactiverse.es4x.ES4X.main(ES4X.java:74)
```
[example](https://github.com/daihy8759/es4x-example)

**Comment by pmlopes** [comment]
In your package.json use `"@es4x/create": "latest"` instead of ` "es4x-pm": "latest"` that should solve the issue.
The issue is a misalignment of versions.
