### ISSUE TITLE
Error when running the packaged jar generate with JVMCI

### ISSUE THREAD

**Issue by abner** [reactiverse/es4x#57]
I just packaged a jar with `JVMCI=1 npm run package`, but when i run the command to start the jar:

```bash
/home/abner2/.sdkman/candidates/java/11.0.1-open/bin/java \
  --module-path=target/compiler \
  -XX:+UnlockExperimentalVMOptions \
  -XX:+EnableJVMCI --enable-preview \
  --upgrade-module-path=target/compiler/compiler.jar \
  -jar target/es4x-java11-1.0.0-bin-jvmci.jar
```

I'm facing this exception:

```
org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: No language for id regex found. Supported languages are: [js]
        at <js> :anonymous(Unknown)
        at <js> :program(console.js:16-183:608-5011)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:331)
        at io.reactiverse.es4x.impl.graal.GraalRuntime.<init>(GraalRuntime.java:197)
        at io.reactiverse.es4x.impl.graal.GraalRuntime.<init>(GraalRuntime.java:71)
        at io.reactiverse.es4x.Runtime.getCurrent(Runtime.java:58)
        at io.reactiverse.es4x.VerticleFactory.createVerticle(VerticleFactory.java:43)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:237)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:210)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:177)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:149)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:137)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)
Original Internal Error:
java.lang.IllegalStateException: No language for id regex found. Supported languages are: [js]
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.findLanguage(PolyglotEngineImpl.java:443)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl$EngineImpl.parseForLanguage(PolyglotImpl.java:473)
        at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.parse(TruffleLanguage.java:1787)
        at com.oracle.truffle.js.runtime.JSContext.getRegexEngine(JSContext.java:934)
        at com.oracle.truffle.js.runtime.RegexCompilerInterface.compile(RegexCompilerInterface.java:75)
        at com.oracle.truffle.js.runtime.RegexCompilerInterface.compile(RegexCompilerInterface.java:66)
        at com.oracle.truffle.js.nodes.access.RegExpLiteralNode.execute(RegExpLiteralNode.java:92)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic3(JSWriteCurrentFrameSlotNodeGen.java:149)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:84)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:281)
        at com.oracle.truffle.js.nodes.control.AbstractBlockNode.executeVoid(AbstractBlockNode.java:74)
        at com.oracle.truffle.js.nodes.control.BlockNode.execute(BlockNode.java:62)
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:66)
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:139)
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:289)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:278)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:265)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:247)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:230)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$DispatchedCallNode.executeCall(JSFunctionCallNode.java:1210)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CacheNode.executeCall(JSFunctionCallNode.java:879)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$UninitializedCacheNode.executeCall(JSFunctionCallNode.java:913)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode.executeCall(JSFunctionCallNode.java:246)
        at com.oracle.truffle.js.nodes.function.JSFunctionCallNode$CallNode.execute(JSFunctionCallNode.java:313)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute_generic3(JSWriteCurrentFrameSlotNodeGen.java:149)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.execute(JSWriteCurrentFrameSlotNodeGen.java:84)
        at com.oracle.truffle.js.nodes.access.JSWriteCurrentFrameSlotNodeGen.executeVoid(JSWriteCurrentFrameSlotNodeGen.java:281)
        at com.oracle.truffle.js.nodes.binary.DualNode.execute(DualNode.java:105)
        at com.oracle.truffle.js.nodes.function.FunctionBodyNode.execute(FunctionBodyNode.java:66)
        at com.oracle.truffle.js.nodes.function.FunctionRootNode.executeInRealm(FunctionRootNode.java:139)
        at com.oracle.truffle.js.runtime.JavaScriptRealmBoundaryRootNode.execute(JavaScriptRealmBoundaryRootNode.java:92)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:289)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:278)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:265)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:247)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:230)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
        at com.oracle.truffle.js.parser.JavaScriptLanguage$1.execute(JavaScriptLanguage.java:209)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:289)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:278)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:265)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:247)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:223)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:714)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:331)
        at io.reactiverse.es4x.impl.graal.GraalRuntime.<init>(GraalRuntime.java:197)
        at io.reactiverse.es4x.impl.graal.GraalRuntime.<init>(GraalRuntime.java:71)
        at io.reactiverse.es4x.Runtime.getCurrent(Runtime.java:58)
        at io.reactiverse.es4x.VerticleFactory.createVerticle(VerticleFactory.java:43)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:237)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:210)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:177)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:149)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:137)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:380)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)
```

**Comment by pmlopes** [comment]
I believe that I'm missing some jar on the packaging phase... thanks for noting it.

**Comment by pmlopes** [comment]
I've fixed this by reworking the packaging scheme: https://github.com/reactiverse/es4x/commit/b629a54121d20fd89a499e5849dbae468a09baa2 Instead of shading all dependencies are copied to a `target/dist` directory, this will make building faster, and also if later on docker is used, also faster as just the final jar needs to be updated in the image layer instead of the full blob.

**Comment by pmlopes** [comment]
@abner, I've been trying to make the whole dev experience easier and have this #60 

you can run:

```
npm run package
```

And it will dump all required jars in `target/dist` and if you're a docker user:

```
npm run package -- -d
```

And it will produce a container with all stuff you need inside, to keep it small I'm using jdk12-alpine to generate a custom `jlink` image. If say that 12 is to edge, I can switch to 11 but then the base image is not alpine but something else with glibc which will make it slightly bigger.

**Comment by Harinath2306** [comment]
Hi,

I have a similar project which builts jar using graavm. Im facing similar error "java.lang.IllegalStateException: No language for id regex found. Supported languages are: [js]" while run using jar but it works on IntelliJ.

This project works fine when run on IntelliJ but gives error when run using Jar

I don't have any file as language in my project. Can you please help me to make the necessary changes to resolve this issue. Attaching the project for reference.
[GraalVmDependency.zip](https://github.com/reactiverse/es4x/files/5544231/GraalVmDependency.zip)

Any help would be appreciated. Thanks in Advance.

**Comment by pmlopes** [comment]
@Harinath2306 in intellij your IDE runs using your maven pom configuration, which loads the right dependencies from the internet. Your build has some strange single jar file in the classes directory and this isn't enough, plus isn't supposed to be used like that.
You need to add all the dependency jars to your application classpath, the vm will not explode the internal jars or know how to handle them.
