### ISSUE TITLE
Promise of vertx cannot call then twice or more.

### ISSUE THREAD

**Issue by fantasy0v0** [reactiverse/es4x#587]
```shell
$ es4x versions
VM:        OpenJDK 64-Bit Server VM - 17
VM Vendor: null
Vert.x:    4.2.2
ES4X:      0.16.2
graaljs:   21.3.0
```

code: index.js
```javascript
let promise = VPromise.promise();
promise.future().then(v => {
  console.log("v:" + v);
  return "v2";
}, (e) => {
  console.log("err");
}).then(v => {
  console.log("v2:" + v);
  return "v3";
}, (e) => {
  console.log("err");
});
```

error message:
```shell
Failed in deploying verticle caused by TypeError: Cannot read property 'then' of null
        at <js> :anonymous(/C:/Users/fan/Desktop/test/demo/index.js:21-31:412-606)
        at <js> _load(node_modules\.lib\es4x-0.16.2.jar!\io\reactiverse\es4x\jvm-npm.js:73:2195-2276)
        at <js> runMain(node_modules\.lib\es4x-0.16.2.jar!\io\reactiverse\es4x\jvm-npm.js:85:2567-2611)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:934)
        at io.reactiverse.es4x.impl.JSVerticleFactory$1.lambda$start$0(JSVerticleFactory.java:85)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by fantasy0v0** [comment]
[then of io.reactiverse.es4x.Thenable](https://github.com/reactiverse/es4x/blob/develop/es4x/src/main/java/io/reactiverse/es4x/Thenable.java#L37) Maybe should return Value.

**Comment by fantasy0v0** [comment]
> [then of io.reactiverse.es4x.Thenable](https://github.com/reactiverse/es4x/blob/develop/es4x/src/main/java/io/reactiverse/es4x/Thenable.java#L37) Maybe should return new Future.
> 
> ![image](https://user-images.githubusercontent.com/9549027/169078407-cf6c575e-d056-4f36-90a7-88387c8fad3a.png)

I tried to modify it, but the problem was not simple.😣https://promisesaplus.com/#the-then-method
