### ISSUE TITLE
Cannot Resolve the CWD error when path contains spaces in windows

### ISSUE THREAD

**Issue by bkoripalli** [reactiverse/es4x#590]
Running my application from Program Files my app crashed with below error due to space in CWD.

error:java.lang.IllegalArgumentException: Cannot resolve the CWD
Caused by: java.net.URISyntaxException: Illegal character in path at index 18: file:///C:/Program Files/RESTService/bin/ ->
at [java.base/java.net.URI$Parser.fail(URI.java:2913)](http://java.base/java.net.URI$Parser.fail(URI.java:2913)) ->
at [java.base/java.net.URI$Parser.checkChars(URI.java:3084)](http://java.base/java.net.URI$Parser.checkChars(URI.java:3084)) ->
at [java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)](http://java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)) ->
at [java.base/java.net.URI$Parser.parse(URI.java:3114)](http://java.base/java.net.URI$Parser.parse(URI.java:3114)) ->
at java.base/java.net.URI.<init>(URI.java:600) ->
at io.reactiverse.es4x.impl.Utils.fileToURI(Utils.java:98) ->
... 31 common frames omitted ->

**Comment by pmlopes** [comment]
Fixed by #591
